gpii-ops/exekube

modules/gke-network/main.tf
Without this, API management code fails after up/down/up.
My PR against upstream has more details about why I did this:
https://github.com/exekube/exekube/pull/91
=> Set disable_on_destroy=true for API management.

modules/helm-release/main.tf, modules/helm-release/variables.tf
Right now the only way to pass release values to `helm-release` module is by providing `release_values.yaml` file, which is not very convenient or secure. This adds functionality for `helm-release` module to accept pre-rendered data via `release_values_rendered` variable.
I double checked and this does not break existing functionality of the module.
=> Add release_values_rendered to helm-release module

modules/helm-release/main.tf
I know, it looks like a really complicated fix for such a trivial issue, but believe me, there is no better way :)
Terraform will always fail during Helm provider configuration (which happens during `:destroy` as well) if certificate files not present on disk (already removed during previous `:destroy`) with:
```
Error: module.gpii-flowmanager.provider.helm: file: open /project/live/dev/secrets/kube-system/helm-tls/ca.cert.pem: no such file or directory in:
${file("${var.client_auth}/ca.cert.pem")}
```
And there is no way to evaluate if local file is present on disk in Terraform: https://github.com/hashicorp/terraform/issues/10878.
=> [GPII-3251]: Idempotence for helm-release destroy

modules/gke-cluster/main.tf, modules/gke-cluster/variables.tf
I am exploring monitoring/logging options:
https://cloud.google.com/monitoring/kubernetes-engine/
This is required to enable beta APIs: `monitoring.googleapis.com/kubernetes`, `logging.googleapis.com/kubernetes`.
=> [GPII-2955, GPII-2954]: Make monitoring_service, logging_service customizable for gke-cluster

.dockerignore, dockerfiles/google/Dockerfile, terraform-plugins/providers.tf
This is one of the possible implementations. It works and speed up the execution of the commands, due Terraform does not have to download all the plugins in each subdirectory.
=> GPII-3360 Install Terraform plugins

modules/gke-cluster/main.tf, modules/gke-cluster/variables.tf
Kubernetes Dashboad has been deprecated on GKE (see
https://cloud.google.com/kubernetes-engine/docs/concepts/dashboards) for
details. This adds parameter disable_dashboard to gke-cluster module.
Default (false) will keep current behaviour (Dashboard enabled).
_(Jira ticket is not referenced in the commit message as I want to open PR against upstream once reviewed)_
=> GPII-3339: Add disable_dashboard parameter

.gitlab-ci.yml
Prevent situation like last night where I messed up exekube by pushing a branch to the gpii-ops repo.
=> Only publish builds from master.

modules/helm-release/main.tf, modules/helm-release/variables.tf
This PR makes `force_update` on `helm_release` resource parametrised.
Pre-req for [GPII-3391](https://issues.gpii.net/secure/RapidBoard.jspa?rapidView=21&view=detail&selectedIssue=GPII-3391)
Plan to open PR against upstream once reviewed and add a link here.
=> GPII-3391: Parametrise force_update of helm_release

dockerfiles/alicloud/Dockerfile, dockerfiles/aws/Dockerfile, dockerfiles/google/Dockerfile
Use gpii-ops build of Terraform Helm provider, as it fixes issue with Terraform ignoring `FAILED` releases. See [GPII-3525 JIRA issue](https://issues.gpii.net/browse/GPII-3525), PR https://github.com/gpii-ops/terraform-provider-helm/pull/1 and issue description in upstream repo - https://github.com/terraform-providers/terraform-provider-helm/issues/159 for more details.
I'll also open PR against upstream and once (if) the changes make it there, we should use that. In the meantime the Helm provider has also been adopted as official TF provider, therefore we should move away from using the release from `mcuadros` repo and use official one once this happens.
=> GPII-3525: Use gpii-ops build of Helm provider

modules/gke-cluster/main.tf, modules/gke-cluster/outputs.tf, modules/gke-cluster/variables.tf
This PR:
- Updates provider to `google-beta` one, see https://www.terraform.io/docs/providers/google/provider_versions.html for details
- Add support for regional cluster by adding `region` argument. Only one of `region` and `main_computer_zone` my be set.
This is non-breaking change, if you use and want to keep using zonal cluster, no changes are needed.
Migration - If you already have existing zonal cluster and want to move to regional, you should:
- Set `region` argument
- Unset `main_compute_zone` one
- Move object in Terrafrom state to a new name, such as `terraform state mv google_container_cluster.cluster
google_container_cluster.cluster-regional` before running `terraform apply`. This will still re-create a
cluster, but it should work without manual intervention.
=> GPII-3568: Add support for regional clusters

terraform-plugins/providers.tf
Looks like `google-beta` provider was introduced in #27, but has not been added to the plugin list:
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/134135946
```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "google-beta" (1.19.0)...
```
=> Add google-beta provider to terraform-plugins

modules/gcp-secret-mgmt/main.tf, modules/gcp-secret-mgmt/variables.tf
Required by https://github.com/gpii-ops/gpii-infra/pull/246.
=>  [GPII-3326]: Make adding audit config in gcp-secret-mgmt module configurable

cli/main.go
There are two sets of Terragrunt commands:
- Commands like `apply`, `destroy`, `plan`, `output` does not respect module dependencies.
- Commands like `apply-all`, `destroy-all`, `plan-all`, `output-all` respect module dependencies.
Previous `xk` implementation had two extra aliases (`up` -> `apply`, `down` -> `destroy`) and on top of that appended `-all` postfix to every command.
This PR adds all supported Terragrunt commands to `exekube`, while keeping old aliases (and virtually all existing functionality) for back compatibility.
PS. Not touching the question of why do we need this Go binary here, if everything it does is `cd $2 && terragrunt $1`.
=> [GPII-3616]: Update xk binary to not apply -all postfix to every Terragrunt command

dockerfiles/google/Dockerfile
@amatas Discovered this today, helps to save ~200MB.
Before:
```
gpii/exekube        0.4.0-google        e0f9519dec8b        17 hours ago        1.18GB
```
After:
```
gpii/exekube        0.4.0-google        08cdef03c26e        14 seconds ago      994MB
```
=> Remove GCP SDK backup folder

.gitlab-ci.yml
`publish` was disabled for non-master branches, but that doesn't matter so much when this project and gpii-infra are built on the same CI worker (:
=> Only build master

modules/gke-cluster/main.tf, modules/gke-cluster/variables.tf
When `additional_zones` left blank, it causes issues for regional clusters:
```
module.gke_cluster.google_container_cluster.cluster-regional: Modifying... (ID: k8s-cluster)
additional_zones.#:          "3" => "0"
additional_zones.1988413740: "us-east1-d" => ""
additional_zones.551448234:  "us-east1-b" => ""
additional_zones.969236459:  "us-east1-c" => ""
Error: Error applying plan:
1 error(s) occurred:
* module.gke_cluster.google_container_cluster.cluster-regional: 1 error(s) occurred:
* google_container_cluster.cluster-regional: googleapi: Error 400: Must specify a field to update., badRequest
```
=> [GPII-3697]: Remove additional_zones from cluster-regional

terraform-plugins/providers.tf
This updates Google provider to v2, and is prereq. to https://github.com/gpii-ops/gpii-infra/pull/299 as there are some changes required (see https://www.terraform.io/docs/providers/google/version_2_upgrade.html for details).
=> GPII-3715: Update Google provider to v2

terraform-plugins/providers.tf
PR updates google providers to 2.1. 
This should resolve the issue with stale clusters left behind when the cluster creation fails because of GCP resource exhaustion in given zone/region (see https://github.com/GoogleCloudPlatform/magic-modules/pull/1381 for more details).
=> GPII-3763: Update Google provider to 2.1

modules/gke-cluster/main.tf, modules/gke-cluster/node_pool.tf, modules/gke-cluster/variables.tf
This is 1st part of moving over to Node Pools to manage nodes of GKE Clusters
It's part of the story described in gpii-ops/gpii-infra#327
**This PR**:
- Adds Primary node pool using `google_container_node_pool`
This is (or together with #48 will be) a breaking change, but splitting allows for no-downtime migration process (create new node pool, drain old nodes, delete default node pool).
See gpii-ops/gpii-infra#327 for more details.
=> GPII-3419: Add primary Node Pool

modules/gke-cluster/main.tf, modules/gke-cluster/node_pool.tf, modules/gke-cluster/variables.tf
This is 1st part of moving over to Node Pools to manage nodes of GKE Clusters
It's part of the story described in gpii-ops/gpii-infra#327
**This PR**:
- Removes default GKE Cluster Node Pool
This is a breaking change, but splitting (together with #47) allows for no-downtime migration process (create new node pool, drain old nodes, delete default node pool). 
This PR should be merged only after #47 and gpii-ops/gpii-infra#327. See gpii-ops/gpii-infra#327 for more details.
=>  GPII-3419: Remove default GKE Cluster Node Pool

docker-compose.yaml, dockerfiles/google/Dockerfile, terraform-plugins/providers.tf
This PR:
- updates Terraform
- updates Google Cloud SDK
- updates kubectl
- ~updates Helm~
- updates Terragrunt
- updates all Terraform providers to the latest
- moves to vanilla Helm provider, as the changes we needed have been merged upstream
This mainly fixes node_pool recreation due to metadata config - see https://github.com/GoogleCloudPlatform/magic-modules/pull/1507 for details.
Update:
Helm update was reverted due to an issue with spec validation (see https://github.com/helm/helm/issues/5750). This should be fixed in soon to be 0.14.1, but it was not available at the time of this PR yet.
This should be tagged as `0.6.0-google_gpii.0` once merged.
Also:
- I've tried to upgrade to Alpine 3.9, but failed due to issue with compiling grpc with newer gcc version (see …
=> GPII-3940: Upgrade terrafrom and providers

docker-compose.yaml, modules/gke-cluster/main.tf, modules/gke-cluster/variables.tf
This PR adds support for disabling GKE HTTP (L7) load balancing controller addon, as it's not being used.
Should be tagged as `0.7.1-google_gpii.0` once merged. PR will be opened against upstream once this is reviewed & merged.
=> Disable l7 load balancer

docker-compose.yaml, modules/gke-network/outputs.tf
This PR fixes the output of `gke-network` module when `create_static_ip_address` is set to `false`.
Current error:
```yaml
Error: Error applying plan:
1 error occurred:
* module.gke_network.output.static_ip_address: Resource 'google_compute_address.ingress_controller_ip.0' does not have attribute 'address' for variable 'google_compute_address.ingress_controller_ip.0.address'
```
Should be tagged as `0.7.2-google_gpii.0` once merged. PR will be opened against upstream once this is reviewed & merged.
=> Fix gke-network module output when glopal_ip is disabled

docker-compose.yaml, dockerfiles/google/Dockerfile
This PR updates `kubectl` version to `1.13.8`. Main reason being that 1.13 has the option `--address` available for `port-forward` command, which is required for my work on enabling the access to CouchDB UI ([GPII-4023](https://issues.gpii.net/browse/GPII-4023)).
Once merged, new tag `0.9.0-google_gpii.0` should be created.
PR against upstream will be opened and linked, once this PR is past review.
~@mrtyler I was thinking about merging this PR together with #62, as both are trying to increase minor version, but if that doesn't sound ok I'm happy to bump this to `0.8.1` or `0.9` even.~
=> Update kubectl to 1.13

docker-compose.yaml, modules/gke-cluster/main.tf
I am not sure what was the original intent for this, blame points me to these two commits:
https://github.com/exekube/exekube/commit/14987c5f61bc806356701b994cb8aafc10c00b5b
https://github.com/exekube/exekube/commit/bedea97bfdaf3d251880f70441698d8d2756685f
But description is not helpful to understand the reason.
Anyway, there is no need to touch helm in `gke-cluster`, since there is a separate `helm-initializer` module, and this also breaks things when Helm env vars are set (https://github.com/gpii-ops/gpii-infra/pull/461).
=> Remove helm init from gke-cluster

docker-compose.yaml, modules/helm-initializer/main.tf
This makes `tiller_status` fail faster (by 2m) when it can't reach a cluster (like running `rake destroy` on a non-existing cluster).
Once merged tag `0.9.2-google_gpii.0` should be created.
I plan to open PR against upstream once this is PR is reviewed.
```
bash-4.4# time kubectl get deploy tiller-deploy
Unable to connect to the server: dial tcp 35.226.36.16:443: i/o timeout
real    2m29.933s
user    0m0.090s
sys     0m0.030s
bash-4.4# time kubectl get deploy tiller-deploy --request-timeout 5s
E0731 12:16:33.261546     105 round_trippers.go:174] CancelRequest not implemented by *gcp.conditionalTransport
E0731 12:16:38.264127     105 round_trippers.go:174] CancelRequest not implemented by *gcp.conditionalTransport
E0731 12:16:48.269822     105 round_trippers.go:174] CancelRequest not …
```
=> Fail fast tiller_status

docker-compose.yaml, modules/gke-network/main.tf, modules/gke-network/variables.tf
This PR:
- Removes duplicated firewall rules ([GPII-4061](https://issues.gpii.net/browse/GPII-4061)). GKE creates required rules on its own and these are less open and use target tags.
- Makes `delete_default_network` optional - Terraform has native functionality to do this
New tag `0.9.3-google_gpii.0` will be created once this PR is reviewed and merged, as well as upstream PR.
=> GPII-4061: Remove duplicate firewall rules

.dockerignore, docker-compose.yaml, dockerfiles/google/Dockerfile, gemfiles/google/Gemfile, gemfiles/google/Gemfile.lock
This is a follow-up on https://github.com/gpii-ops/gpii-infra/pull/472.
This also bumps Stackdriver gems to latest versions.
=> [GPII-4057]: Lock gem versions with bundler

docker-compose.yaml, modules/gke-cluster/bin_auth.tf
This PR whitelists GCR registry `gke.gcr.io/istio` used by GKE Istio 1.1 images.
Once merged, tag `0.9.5-google_gpii.0` should be created.
=> Add new Istio GCR registry to whitelist

docker-compose.yaml, modules/gcp-secret-mgmt/main.tf, modules/gcp-secret-mgmt/variables.tf
This PR adds configurable versioning setting for gcp-secret-mgmt GS bucket.
=> [GPII-3836]: Add configurable versioning setting for gcp-secret-mgmt GS bucket

docker-compose.yaml, dockerfiles/google/Dockerfile
This PR adds `ncurses` to support working with colors and other terminal functionality of `tput`.
The image should be tagged as `0.9.8-google-gpii.0` once PR is merged.
=> GPII-4221: Add ncurses for colored output

docker-compose.yaml, modules/gke-cluster/bin_auth.tf
This PR adds missing `gke.grc.io` rule to the Bin-auth whitelisted images patterns and fixes one of the errors observed in [GPII-3850](https://issues.gpii.net/browse/GPII-3850).
```
Failed:
Create pod
kube-proxy-gke-k8s-cluster-terraform-20190319173-571935b8-99sf failed to be created
```
**Changes:**
- Add missing `gke.gcr.io` to bin-auth whitelist
Tag **`0.9.9-google_gpii.0`** shall be created once this PR is merged.
=> Fix missing gke gcr io

modules/gke-cluster/bin_auth.tf
This PR adds missing `gke.grc.io/istio/prometheus/*` rule to the Bin-auth whitelisted images and
fixes the additional error observed, part of [GPII-3850](https://issues.gpii.net/browse/GPII-3850).
```
pods "promsd-76f8d4cff8-6jmsv" is forbidden: image policy webhook backend denied one or more images: Denied by default admission rule. Overridden by evaluation mode. Denied by default admission rule. Overridden by evaluation mode
```
**Changes:**
- Add missing `gke.gcr.io/istio/prometheus/*` to bin-auth whitelist
Tag **`0.9.10-google_gpii.0`** shall be created once this PR is merged.
=> GPII-3850: Add missing gke.gcr.io/istio/prometheus/  to bin-auth whitelist

cli/main.go, docker-compose.yaml, dockerfiles/google/Dockerfile, terraform-plugins/providers.tf
This PR updates the Google Terraform providers and the Google Cloud SDK with the hope of make more reliable every deployment process.
Tag **`0.9.11-google_gpii.0`** shall be created once this PR is merged.
=> [GPII-3718] Update Google Terraform providers and Google Cloud SDK

modules/gcp-secret-mgmt/variables.tf, modules/gcp-stackdriver-export/main.tf, modules/gcp-stackdriver-export/variables.tf
This PR adds support for configuring access-logs for stackdriver export module.
**Changes:**
- Add support for access logs (`exported_logs_access_log_bucket) for `gcp-stackdriver-export/main.tf ` module
Tag **`0.9.12-google_gpii.0`** shall be created once this PR is merged.
=> Add support for access logs for stackdriver exports
